name: Plan & apply

on: 
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"
  push:
    branches: [main]
    paths: 
      - "terraform/**"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: terraform init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=tf-gha-state-amansrsnv132321321" \
            -backend-config="key=${{ matrix.env }}/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=tf-gha-lock" \
            -backend-config="encrypt=true"

      - name: terraform plan
        working-directory: terraform
        run: terraform plan -var-file="envs/${{ matrix.env }}.tfvars"

  apply:
    runs-on: ubuntu-latest
    needs: plan
    if: github.event_name == 'push'
    strategy:
      matrix:
        env: [dev, prod]
    environment: ${{ matrix.env }}


    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: terraform init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=tf-gha-state-amansrsnv132321321" \
            -backend-config="key=${{ matrix.env }}/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=tf-gha-lock" \
            -backend-config="encrypt=true"

      - name: terraform apply -auto-approve
        working-directory: terraform
        run: terraform apply -auto-approve -var-file="envs/${{ matrix.env }}.tfvars"


